=== fkie/ietf-restconf-testcases/tests/test_schemata.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
    "description": "JSON document describing a RESTCONF (RFC 8040) testcase",
    "type": "object",
    "required": ["name", "yangdirs", "model", "before", "query", "response", "after"],
    "properties": {
        "name": {
            "description": "Name of the testcase",
            "type": "string"
        },
        "yangdirs": {
            "description": "Array of directories where the YANG library and schemata are stored",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "model": {
            "description": "File with the yang library model used for the test",
            "type": "string"
        },
        "before": {
            "description": "JSON or XML file with the database state before the test",
            "type": "string"
        },
        "query": {
            "description": "Restconf query from client to server",
            "type": "object",
            "required": ["operation", "url", "headers", "body"],
            "properties": {
                "operation": {
                    "description": "HTTP operation of the query",
                    "type": "string",
                    "enum": ["OPTIONS", "HEAD", "GET", "PUT", "POST", "DELETE", "PATCH" ]
                },
                "url": {
                    "description": "URL of the query relative to /restconf",
                    "type": "string"
                },
                "headers": {
                    "descriptions": "Dictionary of HTTP headers to set for the query",
                    "type": "object",
                    "additionalProperties": { "type": "string" }
                },
                "body": {
                    "description": "File with HTTP body of the query or NULL for no body",
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            }
        },
        "rpc": {
            "description": "Remote procedure call necessary for query",
            "type": "object",
            "required": [ "datapath", "input", "output-status", "output" ],
            "properties": {
                "datapath": {
                    "description": "Schema data-path that the RPC should handle",
                    "type": "string"
                },
                "input": {
                    "description": "File with expected input of the RPC or NULL for no input",
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "output": {
                    "description": "File with output of the RPC or NULL for no output",
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            }
        },
        "response": {
            "description": "Restconf response from server to client",
            "type": "object",
            "required": ["status", "headers", "body"],
            "properties": {
                "status": {
                    "description": "HTTP Return code",
                    "type": "integer",
                    "minimum": 100,
                    "maximum": 999
                },
                "headers": {
                    "descriptions": "Dictionary of HTTP headers to set for the query",
                    "type": "object",
                    "additionalProperties": { "type": "string" }
                },
                "body": {
                    "description": "File with HTTP body of the response or NULL for no body",
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            }
        },
        "after": {
            "description": "JSON or XML file with the database state after the test",
            "type": "string"
        }
    }
}

=== fkie/ietf-restconf-testcases/tests/test_example_1_root/test.json
{
    "name": "get whole data directory",
    "yangdirs": [ "../../yang-models/example_1" ],
    "model": "../../yang-models/example_1/example1.json",
    "before": "state.json",
    "query": {
        "operation": "GET",
        "url": "/data/ex353:top",
        "headers": {
            "Accept": "application/yang-data+json"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "result.json"
    },
    "after": "state.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_b_3_4_json/test.json
{
    "name": "RFC 8040 Section B.3.4. json example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/jukebox.json",
    "before": "before.json",
    "query": {
        "operation": "POST",
        "url": "/data/example-jukebox:jukebox/playlist=Foo-One?insert=first",
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "query.json"
    },
    "response": {
        "status": 201,
        "headers": {
        },
        "body": null
    },
    "after": "after.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_3_3_3_json/test.json
{
    "name": "RFC 8040 Section 3.3.3. json example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/jukebox.json",
    "before": "state.json",
    "query": {
        "operation": "GET",
        "url": "/yang-library-version",
        "headers": {
            "Accept": "application/yang-data+json"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "result.json"
    },
    "after": "state.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_4_1/test.json
{
    "name": "RFC 8040 Section 4.1. example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/jukebox.json",
    "before": "state.json",
    "query": {
        "operation": "OPTIONS",
        "url": "",
        "headers": {
            "Accept": "application/yang-data+json"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Accept-Patch": "application/yang-data+json",
            "Allow": "OPTIONS, HEAD, GET, PUT, POST, DELETE, PATCH"
        },
        "body": null
    },
    "after": "state.json"
}

=== fkie/ietf-restconf-testcases/tests/test_tacacsplus_xml/test.json
{
    "name": "Tacacsplus test",
    "yangdirs": [ "../../yang-models/ietf" ],
    "model": "../../yang-models/ietf/tacacsplus-library.json",
    "before": "before.xml",
    "query": {
        "operation": "GET",
        "url": "/data/ietf-system:system",
        "headers": {
            "Accept": "application/yang-data+xml"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+xml"
        },
        "body": "result.xml"
    },
    "after": "after.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_3_3_1_xml/test.json
{
    "name": "RFC 8040 Section 3.3.1. xml example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/jukebox.json",
    "before": "state.json",
    "query": {
        "operation": "GET",
        "url": "/data/example-jukebox:jukebox/library?content=nonconfig",
        "headers": {
            "Accept": "application/yang-data+xml"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+xml"
        },
        "body": "result.xml"
    },
    "after": "state.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_b_3_2_depth1_json/test.json
{
    "name": "RFC 8040 Section B.3.2. depth=1 json example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/jukebox.json",
    "before": "state.json",
    "query": {
        "operation": "GET",
        "url": "/data/example-jukebox:jukebox?depth=1",
        "headers": {
            "Accept": "application/yang-data+json"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "result.json"
    },
    "after": "state.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_b_3_2_unlimited_json/test.json
{
    "name": "RFC 8040 Section B.3.2. depth=unlimited json example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/library.json",
    "before": "state.json",
    "query": {
        "operation": "GET",
        "url": "/data/example-jukebox:jukebox?depth=unbounded",
        "headers": {
            "Accept": "application/yang-data+json"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "state.json"
    },
    "after": "state.json"
}
