=== fkie/ietf-restconf-testcases/tests/test_schemata.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
    "description": "JSON document describing a RESTCONF (RFC 8040) testcase",
    "type": "object",
    "required": ["name", "yangdirs", "model", "before", "query", "response", "after"],
    "properties": {
        "name": {
            "description": "Name of the testcase",
            "type": "string"
        },
        "yangdirs": {
            "description": "Array of directories where the YANG library and schemata are stored",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "model": {
            "description": "File with the yang library model used for the test",
            "type": "string"
        },
        "before": {
            "description": "JSON or XML file with the database state before the test",
            "type": "string"
        },
        "query": {
            "description": "Restconf query from client to server",
            "type": "object",
            "required": ["operation", "url", "headers", "body"],
            "properties": {
                "operation": {
                    "description": "HTTP operation of the query",
                    "type": "string",
                    "enum": ["OPTIONS", "HEAD", "GET", "PUT", "POST", "DELETE", "PATCH" ]
                },
                "url": {
                    "description": "URL of the query relative to /restconf",
                    "type": "string"
                },
                "headers": {
                    "descriptions": "Dictionary of HTTP headers to set for the query",
                    "type": "object",
                    "additionalProperties": { "type": "string" }
                },
                "body": {
                    "description": "File with HTTP body of the query or NULL for no body",
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            }
        },
        "rpc": {
            "description": "Remote procedure call necessary for query",
            "type": "object",
            "required": [ "datapath", "input", "output-status", "output" ],
            "properties": {
                "datapath": {
                    "description": "Schema data-path that the RPC should handle",
                    "type": "string"
                },
                "input": {
                    "description": "File with expected input of the RPC or NULL for no input",
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "output": {
                    "description": "File with output of the RPC or NULL for no output",
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            }
        },
        "response": {
            "description": "Restconf response from server to client",
            "type": "object",
            "required": ["status", "headers", "body"],
            "properties": {
                "status": {
                    "description": "HTTP Return code",
                    "type": "integer",
                    "minimum": 100,
                    "maximum": 999
                },
                "headers": {
                    "descriptions": "Dictionary of HTTP headers to set for the query",
                    "type": "object",
                    "additionalProperties": { "type": "string" }
                },
                "body": {
                    "description": "File with HTTP body of the response or NULL for no body",
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            }
        },
        "after": {
            "description": "JSON or XML file with the database state after the test",
            "type": "string"
        }
    }
}

=== fkie/ietf-restconf-testcases/tests/test_8040_4_7/test.json
{
    "name": "RFC 8040 Section 4.7. example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/library.json",
    "before": "before.json",
    "query": {
        "operation": "DELETE",
        "url": "/data/example-jukebox:jukebox/library/artist=Foo%20Fighters/album=Wasting%20Light",
        "headers": {
        },
        "body": null
    },
    "response": {
        "status": 204,
        "headers": {},
        "body": null
    },
    "after": "after.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_b_3_3_json/test.json
{
    "name": "RFC 8040 Section B.3.3. json example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/jukebox.json",
    "before": "state.json",
    "query": {
        "operation": "GET",
        "url": "/data?fields=ietf-yang-library:modules-state/module(name;revision)",
        "headers": {
            "Accept": "application/yang-data+json"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "result.json"
    },
    "after": "state.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_b_1_2/test.json
{
    "name": "RFC 8040 Section B.1.2. json example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/jukebox.json",
    "before": "before.json",
    "query": {
        "operation": "GET",
        "url": "/data/ietf-yang-library:modules-state",
        "headers": {
            "Accept": "application/yang-data+json"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "response.json"
    },
    "after": "after.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_4_5_json/test.json
{
    "name": "RFC 8040 Section 4.5. json example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/library.json",
    "before": "before.json",
    "query": {
        "operation": "PUT",
        "url": "/data/example-jukebox:jukebox/library/artist=Foo%20Fighters/album=Wasting%20Light",
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "query.json"
    },
    "response": {
        "status": 204,
        "headers": {},
        "body": null
    },
    "after": "after.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_b_1_1_xml/test.json
{
    "name": "RFC 8040 Section B.1.1. xml example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/library.json",
    "before": "before.json",
    "query": {
        "operation": "GET",
        "url": "",
        "headers": {
            "Accept": "application/yang-data+xml"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+xml"
        },
        "body": "response.xml"
    },
    "after": "after.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_b_3_9_report_all/test.json
{
    "name": "RFC 8040 Section B.3.9. trim json example",
    "yangdirs": [ "../../yang-models/rfc6243-interfaces" ],
    "model": "../../yang-models/rfc6243-interfaces/example-interfaces.json",
    "before": "state.json",
    "query": {
        "operation": "GET",
        "url": "/data/example:interfaces/interface=eth1?with-default=report-all",
        "headers": {
            "Accept": "application/yang-data+json"
        },
        "body": null
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/yang-data+json"
        },
        "body": "result.json"
    },
    "after": "state.json"
}

=== fkie/ietf-restconf-testcases/tests/test_8040_4_5_xml/test.json
{
    "name": "RFC 8040 Section 4.5. xml example",
    "yangdirs": [ "../../yang-models/rfc8040-jukebox" ],
    "model": "../../yang-models/rfc8040-jukebox/jukebox.json",
    "before": "before.json",
    "query": {
        "operation": "PUT",
        "url": "/data/example-jukebox:jukebox/library/artist=Foo%20Fighters/album=Wasting%20Light",
        "headers": {
            "Content-Type": "application/yang-data+xml"
        },
        "body": "query.xml"
    },
    "response": {
        "status": 204,
        "headers": {},
        "body": null
    },
    "after": "after.json"
}
